name: SurvivalPlus
author: Mr_Rhetorical
version: 0.2.0
main: com.rhetorical.survival.SurvivalPlus
commands:
  togglePvP:
    usage: /togglePvP
    description: Command to toggle reciprocal player damage.
  pingl:
    usage: /pingl (player)
    description: Pings the target player to get their location.
permissions: {}
api-version: 1.13